name = "optim"
uuid = "5e94efc7-f3d5-4fff-9377-5f5bbfbae52d"
authors = ["hugogarcia06 <hugogmodet06@outlook.com>;<>i.binsenser@upm.es"]
version = "1.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
